### PR TITLE
Upgrade to ueberauth 0.7

### PR DESCRIPTION
**Pull request by wkirschbaum**
0.7 adds support for handling csrf: https://github.com/ueberauth/ueberauth/commit/5c297f1d7574a034b2117a4f6ffb3075ca66d359

Having custom code is not required anymore and also breaks ueberauth_cognito when using ueberauth 0.7, as the cookie must be set.

### CODE REVIEW

**Review by losvedir — CHANGES_REQUESTED** [review]
Thank you so much for your PR! This is great. I hadn't realized that `ueberauth` obviated the need for us to do the random `state` tracking ourselves.

Can you make a couple changes for me (force pushing up the new commits)?

1. Separate out the formatting changes into their own commit. Please run `mix format` in the repo root folder; it looks like there's a couple other files not included here that could use updated formatting. 
2. Include your main functional changes in a second commit. In that second commit, please also update `CHANGELOG.md` and the versions specified in `README.md`.

Once you've updated the PR with those changes, I'll merge it and release a new version on hex.pm. Thanks again!

**Comment by wkirschbaum** [comment]
@losvedir  happy to be able to help. I forced pushed the changes as requested, hope it makes sense.

**Review by losvedir — APPROVED** [review]
Looks good to me. I tried this out on one of our applications and everything seemed to be in order. Thanks so much for your contribution! 🚀

**Comment by losvedir** [comment]
Released on [hex.pm as 0.3.0](https://hex.pm/packages/ueberauth_cognito/0.3.0).

**Pull request merged**
